# Generated by Django 3.0.4 on 2020-03-25 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CabDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Cab')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Cab')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Rider')),
            ],
        ),
    ]
